name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run pack

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(git describe --tags)" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: web-ext-artifacts/wordwise-${{ steps.get_version.outputs.VERSION }}.zip
